export default {
	Home: require('@assets/icons/ic-home.png'),
	HomeFill: require('@assets/icons/ic-home-fill.png'),
	Task: require('@assets/icons/ic-task.png'),
	TaskFill: require('@assets/icons/ic-task-fill.png'),
	Notification: require('@assets/icons/ic-notification.png'),
	NotificationFill: require('@assets/icons/ic-notification-fill.png'),
	User: require('@assets/icons/ic-user.png'),
	UserFill: require('@assets/icons/ic-user-fill.png'),
	Timer: require('@assets/icons/ic-timer.png'),
	Document: require('@assets/icons/ic-document.png'),
	DocumentCheck: require('@assets/icons/ic-document-check.png'),
	RightArrow: require('@assets/icons/ic-right-arrow.png'),
	Back: require('@assets/icons/ic-back.png'),
	Search: require('@assets/icons/ic-search.png'),
	First: require('@assets/icons/ic-first.png'),
	Previous: require('@assets/icons/ic-previous.png'),
	Next: require('@assets/icons/ic-next.png'),
	Last: require('@assets/icons/ic-last.png'),
}
